#
# Makefile for the Linux network (ethercard) device drivers.
#
obj-$(CONFIG_NET) += Space.o loopback.o

obj-$(CONFIG_E1000) += e1000.o

e1000-objs := e1000_main.o e1000_hw.o e1000_ethtool.o e1000_param.o
