#
# Makefile for the mouse drivers.
#

# Each configuration option enables a list of files.
obj-$(CONFIG_MOUSE_PS2)		+= psmouse.o

psmouse-objs  := psmouse-base.o alps.o logips2pp.o synaptics.o lifebook.o trackpoint.o
