#
# Makefile for the input core drivers.
#

# Each configuration option enables a list of files.

obj-$(CONFIG_SERIO)		+= serio.o
obj-$(CONFIG_SERIO_I8042)	+= i8042.o
obj-$(CONFIG_SERIO_LIBPS2)	+= libps2.o
